# This is a basic workflow to help you get started with Actions

name: PacBrew

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install pacbrew-pacman dependencies
      - name: Install pacbrew-pacman dependencies
        run: sudo apt-get install -y git build-essential automake autoconf libtool meson ninja-build libarchive-dev gettext
      # Clone pacbrew-pacman
      
      # Install pacbrew-pacman
      - name: Install pacbrew-pacman
        run: |
          git clone https://github.com/PacBrew/pacbrew-pacman.git
          cd pacbrew-pacman
          meson --prefix=/opt/pacbrew/pacman --sysconfdir=/opt/pacbrew/pacman/etc \
            --localstatedir=/opt/pacbrew/pacman/var -Dpkg-ext=.pkg.tar.xz \
            -Dmakepkg-template-dir=/opt/pacbrew/usr/share/makepkg-template build
          ninja -C build
          ninja -C build install
          
      # Install pacbrew-packages dependencies
      #- name: Install pacbrew-packages dependencies
      #  run: sudo apt-get install -y git build-essential automake autoconf libtool meson ninja-build libarchive-dev gettext

      # Build pacbrew-packages
      - name: Build pacbrew-packages
        run: pacbrew.sh build
