# This is a basic workflow to help you get started with Actions

name: PacBrew

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container: cpasjuste/pacbrew:latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Install ssh key for new package upload to pacbrew repo
      # https://zellwk.com/blog/github-actions-deploy
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: '# dummy'
      - name: Adding ssh key to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/pacbrew/.ssh/known_hosts
          chown pacbrew:pacbrew /home/pacbrew/.ssh/known_hosts
      # Update pacbrew repo
      - name: Update pacbrew repo and packages
        run: pacman -Sy && pacman -S --noconfirm --needed ps4-openorbis ps4-openorbis-portlibs

      # Build pacbrew-packages as "pacbrew" user (needed for makepkg)
      - name: Build pacbrew-packages
        run: |
          chown -R pacbrew:pacbrew "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE" && su -c "./pacbrew.sh" -g pacbrew pacbrew
        #-u ${{ secrets.SSH_USER }} -h ${{ secrets.SSH_HOST }}
