# This is a basic workflow to help you get started with Actions

name: PacBrew

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      # Install pacbrew-pacman
      - name: Install pacbrew-pacman
        run: |
          wget https://github.com/PacBrew/pacbrew-pacman/releases/download/pacbrew-release-1.0/pacbrew-pacman-1.0.deb
          sudo dpkg -i pacbrew-pacman-1.0.deb
          
      # Install pacbrew-packages build dependencies
      - name: Install pacbrew-packages build dependencies
        run: sudo apt-get install -y git build-essential automake autoconf libtool libarchive-tools

      # Build pacbrew-packages
      - name: Build pacbrew-packages
        run: |
          cd $GITHUB_WORKSPACE
          ./pacbrew.sh
